server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    port: 465
    default-encoding: utf-8
    host: smtp.163.com
    username: q17871152478@163.com
    password: FMQuR359jhxrhYaW
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            required: true
            protocols: TLSv1.2
        debug: true
mybatis:
  mapper-locations=classpath:/mappers/*.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.ecommerce: debug
